import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import StoreProvider from "@/store/StoreProvider";
import QueryProvider from "@/providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <StoreProvider>
            <nav style={{ padding: "1rem", borderBottom: "1px solid #ddd" }}>
              <Link href="/">Home</Link>
              {" | "}
              <Link href="/products">Catalog</Link>
              {" | "}
              <Link href="/cart">Cart</Link>
              {" | "}
              <Link href="/admin/login">Login</Link>
            </nav>
            {children}
          </StoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
